(setq frame-resize-pixelwise t)
(load-theme 'brutalist)
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
(defalias 'yes-or-no-p 'y-or-n-p)
(setq user-full-name "Alexander, Griffith")
(setq user-email "griffitaj@gmail.com")
(add-hook 'before-save-hook 'whitespace-cleanup)
(setq auto-save-list-file-prefix "~/.emacs.d/autosaves/.saves-")
(setq auto-save-interval 100)
(setq backup-directory-alist '(("." .  "~/.emacs.d/.cache/backup/")))
(setq delete-by-moving-to-trash nil)
(setq version-control t)
(setq kept-old-versions 10)
(setq kept-new-versions 20)
(setq delete-old-versions t)
(setq backup-by-copying t)
(blink-cursor-mode -1)

(setq visible-bell nil)
(setq ring-bell-function (lambda ()
                           (invert-face 'mode-line)
                           (run-with-timer 0.1 nil 'invert-face 'mode-line)))

(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(show-paren-mode 1)
(setq inhibit-startup-message t)
(setq initial-scratch-message "")
(delete-selection-mode)
(electric-pair-mode t)
(setq-default indent-tabs-mode nil)

(global-auto-revert-mode 1)
(add-hook 'dired-mode-hook 'auto-revert-mode)

(require 'counsel)
(global-set-key (kbd "M-x") 'counsel-M-x)

(defun scratch()
  (interactive)
  (switch-to-buffer (get-buffer-create "*scratch*")))

(setq httpd-port 11000)

(global-set-key (kbd "C-x o") 'ace-select-window)
